stages:
  - build
  # - test
  - deploy_dev
  - deploy_prod


build_job:
  image: node:16.15.1
  stage: build
  script:
    - npm --prefix lecture-feedback install
    - CI=false npm --prefix lecture-feedback run build
  artifacts:
    paths:
      - lecture-feedback/build
    expire_in: 1 hour

deploy_dev_job:
  image: ruby:2.7.5
  stage: deploy_dev
  script:
    - cp lecture-feedback/api/requirements.txt .
    - gem install dpl --pre
    - dpl --provider=heroku --app=lecture-feedback-drp-dev --api-key=$HEROKU_API
  only:
     - dev

deploy_prod_job:
  image: ruby:2.7.5
  stage: deploy_prod
  script:
    - cp lecture-feedback/api/requirements.txt .
    - gem install dpl --pre
    - dpl --provider=heroku --app=lecture-feedback-drp --api-key=$HEROKU_API
  only:
     - master
