stages:
  - build
  # - test
  - deploy


build_job:
  image: node:16.15.1
  stage: build
  script:
    - npm --prefix lecture-feedback install
    - npm --prefix lecture-feedback run build

deploy_job:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl --verbose
    - dpl --provider=heroku --app=lecture-feedback-frontend --api-key=$HEROKU_API
