stages:
  - build
  # - test
  - deploy


build_job:
  stage: build
  script:
    - npm --prefix lecture-feedback build

deploy_job:
  image: ruby:latest
  stage: deploy
  script:
    - gem install dpl --verbose
    - dpl --provider=heroku --app=lecture-feedback-frontend --api-key=$HEROKU_API
